### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by dhimmel** [bioinfo-ut/StrainSeeker#1]
Currently, this repo doesn't have an open source license, which is a [problem for users](https://choosealicense.com/no-license/).

From [PeerJ's policies](https://peerj.com/about/policies-and-procedures/):

> For software papers, 'materials' are taken to mean the source code and/or relevant software components required to run the software and reproduce the reported results. The software should be [open source](http://opensource.org/docs/osd), made available under an appropriate license, and deposited in an appropriate archive. Data used to validate a software tool is subject to the same sharing requirements as any data in PeerJ publications.

Personally, I'd recommend a permissive open source license like MIT or BSD 3-Clause.

**Comment by bioinfo-ut** [comment]
Thank you for bringing this up. License should now be added.

**Comment by dhimmel** [comment]
@bioinfo-ut thanks for https://github.com/bioinfo-ut/StrainSeeker/commit/7c2dcda580a55bdfe4938efe67bf27e8927ca0d5 which licensed this repo under a [CC BY-NC-ND 4.0 license](https://creativecommons.org/licenses/by-nc-nd/4.0/). Unfortunately, this is not an open source license. Specifically, the non commercial and no derivative clauses are [antithetical to open source](https://opensource.org/osd).

The Open Source Initiative (which PeerJ's Policies reference) maintains a list of [approved licenses](https://opensource.org/licenses). I'd recommend using one of these licenses for software.
